### ISSUE TITLE
Alert users better to transient errors?

### ISSUE THREAD

**Issue by brendanhoar** [tabit-pro/qubes-windows-tools-cross#11]
```
dotNetFx40_Full_x86_x64.exe
```
 failed to download during one run of Step 2. of the Readme. 

Running step 2 again resolved the issue.

While I happened to notice the error and reran Step 2., it might be wise to include a more noticeable (color, banner, larger etc.) error message so that folks don't go ahead with step 3 without resolving.

B

**Comment by jevank** [comment]
>it might be wise to include a more noticeable (color, banner, larger etc.) error message so that folks don't go ahead with step 3 without resolving

It is qubes-builder part with global FETCH_CMD procedure.

**Comment by jevank** [comment]
I close the issue, feel free to reopen.
