### ISSUE TITLE
Github's git:// protocol is not supported anymore

### ISSUE THREAD

**Issue by Bluesky787** [tabit-pro/qubes-windows-tools-cross#14]
According to GitHub, cloning of repos using git:// protocol is not possible anymore.
When trying to fetch QWT sources and extra binaries, the make command throws errors stating that cloning QubesOS repos failed while providing a link to [GitHub help page](https://github.blog/2021-09-01-improving-git-protocol-security-github/).

The message is:

`Cloning into '/home/user/qubes-builder/qubes-src/windows-tools-cross/qubes-vmm-xen-windows-pvdrivers/xeniface'...
fatal: remote error:      
    The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
fatal: clone of 'git://github.com/QubesOS/qubes-vmm-xen-win-pvdrivers-xeniface.git' into submodule path '/home/user/qubes-builder/qubes-src/windows-tools-cross/qubes-vmm-xen-windows-pvdrivers/xeniface' failed`

It seems that every clone command using git:// protocol must be changed to use https.

Thanks and props for your work!
Bluesky

Edit: provided the error line stating the (first) erroneous git:// url.

**Comment by jevank** [comment]
I cannot reproduce the issue in fedora 34 environment and submodules URL are with https:// protocol.

UPDATE: and now confirm error :)

**Comment by Bluesky787** [comment]
Can I help with more information?
I used fresh Qubes 4.1rc installation and a fresh fedora-34 environment, too.

Edit: Oh, you already fixed it. Thanks!
