### ISSUE TITLE
Win 10 standalone vm seems to have no cdrom drive

### ISSUE THREAD

**Issue by deeplow** [tabit-pro/qubes-windows-tools-cross#21]
I tried following the instructions on the README.md. However no drive was being found. Doing [this solved it](https://forum.qubes-os.org/t/win-10-standalone-vm-seems-to-have-no-cdrom-drive/8645/3) so maybe the `powercfg -H off` should be added?

**Comment by jevank** [comment]
Yes, likely that is required in latest windows. We have included it in QWT setup, but it should be at preparation stage.

**Comment by deeplow** [comment]
I think it's an earlier version of windows 10 (maybe 8 months old).
