### ISSUE TITLE
Fails to build: no release4.1 branch

### ISSUE THREAD

**Issue by gangamstyle** [tabit-pro/qubes-windows-tools-cross#22]
Hi, it fails to build in fedora 34, but I think there is just no release4.1 branch, have you removed it ?

**Comment by jevank** [comment]
Hi, thanks for your feedback. Try with master builder config
```
make BUILDERCONF=example-configs/qubes-os-master.conf COMPONENTS=windows-tools-cross windows-tools-cross-dom0
```

**Comment by gangamstyle** [comment]
Yes, master compiles, ty!
